### ISSUE TITLE
Not working with Ember Pods structure

### ISSUE THREAD

**Issue by harmvandeven** [nathanhammond/ember-route-alias#14]
I couldn't get the simplest aliases to work until I realised the only different thing I was doing was using **Ember Pods**. As soon as I created non-pod routes the aliases started working. Will ember-route-alias be working with Ember Pods in the future and is this a known issue?

**Comment by nathanhammond** [comment]
It is now a known issue, but this will never be designed to support pods. It will eventually support the new module unification proposal. I am willing to accept a PR to add support for pods, however, this is not something I'm going to invest my own time in supporting.
