### ISSUE TITLE
Alias to application route

### ISSUE THREAD

**Issue by danDanV1** [nathanhammond/ember-route-alias#5]
Nathan, can we alias to the application route?

I have the usual nested routes:

```
/section1/subsection1
/section2/subsection2
```

I need to create different paths for internationalization:

```
/au/section1/subsection1
/au/section2/subsection2
/fr/section1/subsection1
/fr/section2/subsection2
```

I want to alias /au and /fr to the application route. 

All the following result in: 
"Assertion Failed: The alias target must exist before attempting to alias it."
this.alias('au', '/au', 'application.index');
this.alias('au', '/au', 'application');
this.alias('au', '/au', 'index');

I'm pretty sure the application route and the application index route exist, so how to alias to them?

**Comment by nathanhammond** [comment]
Unfortunately the `application` and `index` routes are special routes and I didn't really account for them. Any route that is aliased must actually be defined by you. In this case you _can_ alias the `index` route by adding this to your `Router.map`:

```
this.route('index', { path: '/' });
```

There's no good solution for aliasing the `application` route and that is probably not a great idea. I'm going to close this as I don't want to support aliasing the `application` route. :smile:
